import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface AuditReportProps {
  content: string;
}

const AuditReport: React.FC<AuditReportProps> = ({ content }) => {
  // Simple regex to try and extract the score for a visual gauge, purely optional enhancement
  const scoreMatch = content.match(/Score:\s*(\d+)\/100/i) || content.match(/Score:\s*(\d+)%/i);
  const score = scoreMatch ? parseInt(scoreMatch[1], 10) : null;

  return (
    <div className="bg-slate-900 border border-slate-700 rounded-xl overflow-hidden shadow-2xl">
      <div className="bg-slate-800/50 p-6 border-b border-slate-700 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-2xl font-serif font-bold text-white flex items-center gap-2">
            <span className="text-indigo-400">⚖️</span> Legal Audit Report
          </h2>
          <p className="text-slate-400 text-sm mt-1">Generated by EquityEye AI • Gemini 3 Pro</p>
        </div>
        
        {score !== null && (
          <div className="flex items-center gap-3 bg-slate-900 p-3 rounded-lg border border-slate-700">
            <div className="text-right">
              <div className="text-xs text-slate-400 uppercase tracking-wider font-semibold">Founder Score</div>
              <div className={`text-2xl font-bold ${score < 50 ? 'text-red-500' : score < 80 ? 'text-yellow-400' : 'text-green-400'}`}>
                {score}/100
              </div>
            </div>
            <div className="h-12 w-12 rounded-full border-4 border-slate-700 flex items-center justify-center relative">
               <svg className="absolute top-0 left-0 w-full h-full transform -rotate-90">
                 <circle cx="22" cy="22" r="18" stroke="currentColor" strokeWidth="4" fill="none" className="text-slate-800" />
                 <circle 
                    cx="22" 
                    cy="22" 
                    r="18" 
                    stroke="currentColor" 
                    strokeWidth="4" 
                    fill="none" 
                    strokeDasharray="113" 
                    strokeDashoffset={113 - (113 * score) / 100} 
                    className={`${score < 50 ? 'text-red-500' : score < 80 ? 'text-yellow-400' : 'text-green-400'} transition-all duration-1000 ease-out`}
                  />
               </svg>
            </div>
          </div>
        )}
      </div>

      <div className="p-8 max-w-none prose prose-invert prose-headings:font-serif">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {content}
        </ReactMarkdown>
      </div>
    </div>
  );
};

export default AuditReport;
